FROM ubuntu

WORKDIR /root
RUN apt update \
 && apt install -y \
    sudo \
    curl openssh-client rsync socat wget \
    unzip xz-utils zip \
    jq make patch python3 python3-pip python3-venv \
    ed git \
 && rm -rf /var/lib/apt/lists/*
RUN python3 -m venv .venv
ENV PATH="/root/.venv/bin:$PATH"
