name: 🐞 Bug report
description: Create a report to help us reproduce and fix bugs.
title: "[Bug] "
labels: ['bug']

body:
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Run the following command
      2. Observe the output
      3. See the error message
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the problem here.
